# NCEA_groundwater_power_2025




### Introduce repository

The scripts and functions in this repository were created to run power analyses for groundwater monitoring using simulated data. The scripts in this repository consist of a single function which then calls multiple others to do conduct a power analysis. The main function `run_power_analysis` works by modelling current data, extracting the model parameters, simulating data according to an effect size and then modelling those simulated data. From this, we extract the number of times (across all simulations) that the model term of interest was significant and use this as an estimate of power to detect that effect size. The modelling is done using a _gamma_ distribution in the `glmmTMB` package. The function has a number of different options, allowing (some) flexibility in modelling scenarios.

There was initial interest in understanding the relative benefit of telemetered versus dip site data. This function can take multiple datasets as inputs, and the user can specify the proportion of each dataset that is used for modelling. The effect of using different proportions of different data types on the power to detect changes can therefore be assessed.

The function also has the ability to look at trends in two different (continuous) fixed effects. This means that the user can alter the changes over time of two different fixed effects, one for each of the fixed effects included.


### running the function

#### examples

one dataset

```{r}

pwr <- run_power_analysis(
  datasets = "data/processed/dip_data_mn_5yrperc_change.csv", # one or more datasets
  sample_column = "sampled_20",
  site_column = "sampling_point",
  model_pars = c("month", "year", "sampling_point"), ## change this to station_number
  random_effect = c("sampling_point"), ## try with single random effect
  yearly_samfreq = 12,# number of sampling occasions per year, 1 if annual, 12 if monthly
  yearly_samfreq_column = "month",
  response_var = "water_level",
  effect.size = 0.1,
  nsim = 10,
  samfreq = 1,
  nosite.yr = 100, # number of sites sampled per year across all datasets
  noyear = 5,
  data_proportions = NULL, # try with NULL - don't think it would work
  save_loc = NULL)

```

two datasets

two fixed effects

two effect sizes


### detailed explanation

different datasets

-different proportions

different effect sizes for each fixed effect


explain how the function works
(discuss functions that could be useful? or later...?)

model - glmmtmb gamma link
-extract model params
create data template
alter proportions - outputs template for each dataset
simulate data for each of the datasets - combine
run power


parameter specifications

"rules" about fixed effects
coded sequentially i.e. increasing values
present in parameter values 







sub-functions that are useful


simulate data

